### ISSUE TITLE
Optimize Images [Easy]

### ISSUE THREAD

**Issue by ajiteshr7** [JMI-CSI/algorhythm-website#5]
A nice and easy fix for all those looking for a PR.

**Comment by Vaibhavdixit02** [comment]
What is this issue about, can you elaborate please?

**Comment by iharsh234** [comment]
@Vaibhavdixit02  Issue is with loading time, due to size of images , gif and other media. It would be great if you optimized these(lossless compression will work) images.

**Comment by ajiteshr7** [comment]
@Vaibhavdixit02  Ideally, any page should never serve images that are larger than the version that's rendered on the user's screen. Anything larger than that just results in wasted bytes and slows down page load time.
So, please run an audit and resize those images (image compression is not needed).

**Comment by juliocarneiro** [comment]
I minified the images and managed to minify the gif from 5mb to 800kb

**Comment by gane5hvarma** [comment]
is there any data of images for which we need to work?

**Comment by ajiteshr7** [comment]
You can get them by running audit in ChromeDev Tools.

**Comment by orafaelfragoso** [comment]
@ajiteshr7 How is this site hosted? I can setup a gulp script to minify and concatenate scripts and generate a build of the website.

**Comment by iharsh234** [comment]
@rafaelfragosom hosted on github pages.

**Comment by ajiteshr7** [comment]
@rafaelfragosom appreciated your concern. But we won't be needing gulp script (not a part of our workflow here).
If you want, what you can do is try fixing the index page background image animation to something better (adding a slide animation or improving upon current animation).

**Comment by ajiteshr7** [comment]
@rafaelfragosom appreciated your concerns.But gulp script is not a part of our workflow here.

**Comment by orafaelfragoso** [comment]
@ajiteshr7 That's a concern and unproductive. What happens when you change an image, replace a font or even wants to concatenate and minify your scripts? You do this by hand?

When I work with Github Pages, I have a gulp scripts that automates everything and even deploy my page to Github. Let me know if you want something alike.

**Comment by ajiteshr7** [comment]
@rafaelfragosom the webpage is on a "create once, consume once" model and hence gulp is not being used here.
